### ISSUE TITLE
肉眼单测 Control

### ISSUE THREAD

**Issue by lazycal** [bill125/ComputerCompositionExperiment#3]
- [x] ADDIU
- [x] ADDIU3
- [x] ADDSP
- [x] ADDU
- [x] AND
- [x] B
- [x] BEQZ
- [x] BNEZ
- [x] BTEQZ
- [x] CMP
- [x] JR
- [x] LI
- [x] LW
- [x] LW_SP
- [x] MFIH
- [x] MFPC
- [x] MOVE*
- [x] MTIH
- [x] MTSP
- [x] NEG*
- [x] NOP
- [x] NOT*
- [x] OR
- [x] SLL
- [x] SLT*
- [x] SLTUI*
- [x] SRA
- [x] SUBU
- [x] SW
- [x] SW_SP

**Comment by bill125** [comment]
NEG: ALU默认进行无符号数减法，是否会产生问题?
